blog/urls.py
from django.urls import  path
from . import views

# app_name = 'blog'
urlpatterns = [
    path('owner_list/', views.OwnerListView.as_view(), name='owner_list'),
    path('owner_list/<int:pk>/', views.OwnerDetailView.as_view(), name='owner_detail'),
    path('pet_list/', views.PetListView.as_view(), name='pet_list'),
    path('pet_list/<int:pk>/', views.PetDetailView.as_view(), name='pet_detail'),
    path('pet_create/', views.PetCreateView.as_view(), name='pet_create'),
    path('pet_list/<int:pk>/update', views.PetUpdateView.as_view(), name='pet_update'),
    path('pet_list/<int:pk>/delete', views.PetDeleteView.as_view(),  name='pet_delete'),
    path('userHomepage/', views.UserHomepageTemplateView.as_view(), name='userHomepage')


    # path('owner/', views.get_OwnerForm, name='owner'),
    # path('<owner_id>', views.owner_detail, name='owner_detail')
]

djangoGirl/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('admin/', admin.site.urls, name='admin'),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('signup/', views.signuppage, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

]

blog/models.py
from django.db import models


from django.utils import timezone

# Create your models here.

class Owner(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(blank=True, null=True)
    def __str__(self):
        return self.last_name


class Vaccine(models.Model):
    name = models.CharField(max_length = 200)
    date = models.DateTimeField(blank = True, null = True)
    def __str__(self):
        return self.name

class Race(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Pet(models.Model):
    name = models.CharField(max_length=200)
    race = models.ForeignKey('Race', on_delete=models.CASCADE)
    # ID_number = models.PositiveIntegerField()
    date_of_birth=models.DateTimeField(blank=True, null=True)
    owner = models.ForeignKey('Owner', on_delete=models.CASCADE)
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Owner, Pet

class IDForm(forms.Form):
    ID_number = forms.IntegerField(label= 'Enter your pet\'s ID number')

class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = '__all__'

class PetForm(forms.ModelForm):
    class Meta:
        Model=Pet
        fields='__all__'

blog/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from .forms import OwnerForm, PetForm, IDForm
from django.http import HttpResponseRedirect
from .models import Owner, Pet
import datetime

class UserHomepageTemplateView(TemplateView):
    template_name = 'blog/userHomepage.html'

def loginpage(request):
    return render(request, 'registration/login.html')

def signuppage(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def homepage(request):
    if request.method == 'POST':
        form = IDForm(request.POST) #IDForm est un formulaire où le site demande à l'utilisateur l'ID de son pet
        if form.is_valid():
            pet_ID=form.cleaned_data['ID_number']
            return HttpResponseRedirect(reverse('blog:pet_detail', args=(pet_ID,)) ) #retoure à la page de detail du pet dont le ID aété entré dans le formulaire
    else:
        form = IDForm()

    return render(request, 'homepage.html', {'form':form})

#The old way to do it
# def homepage(request):
#     # html = "<html><body>it is now : %s .<html><body>" % now()
#     return render(request, 'homepage.html', {'current_time': now()})

class OwnerListView(ListView): #affiche la page html correspondante nommée owner_list
    model = Owner
    context_object_name = 'owners'  #by default it is owner_list

class OwnerDetailView(DetailView): #affiche la page html owner_detail
    model = Owner
    #by default returns owner but if you want to change it use:
    #context_object_name = 'koukou'
    template_view = 'blog/owner_detail.html'
    context_object_name = 'this_owner'  #by default owner

class PetListView(ListView): #affiche pet_list.html
    #crée la variable pet_list liste des pet (dont le modele est appelé ci-après)
    model = Pet
# def owner_detail(request, owner_id):
#     owner = get_object_or_404(Owner, pk=owner_id)
#     return render(request, 'owner_detail.html', {'owner': owner})
class PetDetailView(DetailView): #lui correspond la page html: pet_detail.html
    model = Pet

class PetCreateView(CreateView): #lui correspond lapage html : pet_create.html (automatiquement créee sur la base du modele pet)
    model = Pet
    fields = ('name', 'race', 'owner')
    success_url = reverse_lazy('blog:pet_list') #page vers laquelle le site retourne une fois l'action de création terminée

class PetUpdateView(UpdateView): #lui correspond la page pet_update.html
    model = Pet
    fields = ('name', 'owner')
    success_url = reverse_lazy('blog:pet_list') #revenir sur la page pet_list une fois que la suppression est faite
#remarque: pet_create.html ,pet_delete.html et pet_update.html ne figurent pas dans le dossier temlate (inclus dnas le process)
class PetDeleteView(DeleteView): #lui correspond lapage pet_delete.html
    model = Pet
    success_url = reverse_lazy('blog:pet_list') #revenir sur la page pet_list une fois que la suppression est faite

#
# def get_pet(request):
#     form = PetForm()
#     if request.method == 'POST':
#         form = PetForm(request.POST)
#         if form.is_valid():
#             form.save(commit=True)
#             return HttpResponseRedirect('/')
#     return render(request, 'pet.html', {'form':form})
#
# def get_OwnerForm(request):
#     form = OwnerForm()
#     if request.method == 'POST':
#         form = OwnerForm(request.POST)
#         if form.is_valid():
#             form.save(commit=True)
#             return HttpResponseRedirect('/')
#         else:
#             print('error form validation')
#
#     return render(request, 'owner.html', {'form': form})
#

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static myStyle.css %}">
     <title>Title</title>
</head>
<body>
<div class="container">
  <ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'homepage' %}">Home</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:owner_list' %}">Owners Listing</a>
  </li>
       <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:pet_list' %}">Pets Listing</a>
  </li>
{# <li class="nav-item">#}
{#    <a class="nav-link" href="{% url 'owner'  %}">Owner registration</a>#}
{#  </li>#}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
  </li>

      {% if user.is_authenticated %}
          <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:pet_create' %}">Register your pet</a>
          </li>

          <li class="nav-item">
    <a class="nav-link" href="{% url 'password_change' %}">Change Password</a>
  </li>
      <li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
  </li>
          {% else %}
             <li class="nav-item">
    <a class="nav-link" href="{% url 'signup' %}">Sign up</a>
  </li>
            <li class="nav-item">
    <a class="nav-link" href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
     </ul>
</div>

<img src={% static "images/lapro1.jpg" %}
height:30%
width=30%
     align="left"
>
<img/>

<div class="container">
       {% block body_block %}

    {% endblock %}

</div>
  </body>


</html>

templates/blog/owner_detail.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
<div class="container">
    <ul>
        <li>name: {{ this_owner.last_name }}</li>
        <li>first_name: {{ this_owner.first_name }}</li>
        <li>email: {{ this_owner.email }}</li>
    </ul>
</div>
    <h3>List of Mr {{ this_owner.last_name }}  pets</h3>

    <ol>
        {% for pet in this_owner.pet_set.all %}
    <li>{{ pet.name }}</li>
     {% endfor %}
    </ol>

{% endblock %}

templates/blog/owner_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
{% for owner in owners %}
    <ul>
    <li><a href="{{ owner.id }}/">{{ owner.last_name }} ,{{ owner.first_name }}</a> </li>
    </ul>

{% endfor %}
{% endblock %}

templates/blog/pet_confirm_delete.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
<h1>Are you sure you want to delete {{ pet.name }} ?</h1>
<form method="POST">
{% csrf_token %}
<input type="submit" class="btn btn-danger" value="Delete">
</form>
<a href="{% url 'blog:pet_detail' pet.id %}" >Cancel</a>
{% endblock %}

templates/blog/pet_detail.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
    <div class="container">

   <h2>{{ pet.id }}_ {{ pet.name }} is a {{ pet.race }}</h2>
    <h3>His owner is: mr {{ pet.owner }}</h3>
        <a href="{% url 'blog:pet_update'  pet.id %}"><button type="button" class="btn btn-primary">Update</button></a>
        <a href="{% url 'blog:pet_delete'  pet.id %}"><button type="button" class="btn btn-danger">Delete</button></a>

    </div>

{% endblock %}

templates/blog/pet_form.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
<form method="POST">
{% csrf_token%}
{{ form.as_p }}
<input type="submit" value="submit">
</form>
{% endblock %}

templates/blog/pet_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
{% for pet in pet_list %}
    <ul>
    <li>ID {{ pet.id }} <a href="{{ pet.id }}/"> {{ pet.name }},  {{ pet.race }}</a></li>
    </ul>

    {% endfor %}
{% endblock %}

templates/blog/userHomepage.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block body_block %}
<h1>Welcome to {{ user.username }}</h1>
{% endblock %}

templates/homepage.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block body_block %}
    {% load static %}
    <head>
    <title>Home</title>
    </head>

{#<h1> Current time: {{ current_time }}</h1>#}
{% if user.is_authenticated %}
    <h2>Welcome to {{ user.username }} in the Pet Check Up page!</h2>
    <p>
            <form method="post">
 {% csrf_token %}
     {{ form.as_p }}
    <input type="submit" value="OK">
</form>

    </p>



    {% else %}
        <h2>Welcome to our visitor in the Pet Check Up page!</h2>
 {% endif %}


{% endblock %}